### ISSUE TITLE
Problem In training the FFHQ1024 model 

### ISSUE THREAD

**Issue by VIROBO-15** [apple/ml-gmpi#11]
Hi......

I have some problem in training the FFHQ1024 Model. I have been training the model on 8 NVIDIA A100 GPUs, 40GB Memory still I am getting a error after some iterations of training.

```
Progress to next stage:   0%|          | 657/200000 [2:05:43<602:34:30, 10.88s/it][A
Total progress:   0%|          | 1/3000 [2:06:06<6303:11:19, 7566.35s/it]
Total progress:   0%|          | 1/3000 [2:06:06<6303:11:48, 7566.36s/it]

Progress to next stage:   0%|          | 0/200000 [2:05:55<?, ?it/s]
[Experiment: ./experiments/seed_123-dist_8-FFHQ1024-torgba_cond_normalize_add_z-embed_func_modulated_lrelu-20220727_205418050892] [Epoch: 0/3000] [D loss: 0.7179927229881287] [G loss: 1.4626858234405518] [Step: 620] [Img Size: 1024] [Batch Size: 4] [TopK: 2] Loading extension module upfirdn2d_plugin...
Done setting up PyTorch plugin "upfirdn2d_plugin".

Progress to next stage:   0%|          | 0/200000 [2:05:55<?, ?it/s]
Loading extension module upfirdn2d_plugin...
Done setting up PyTorch plugin "upfirdn2d_plugin".


Total progress:   0%|          | 1/3000 [2:06:06<6303:14:46, 7566.42s/it]
Setting up PyTorch plugin "bias_act_plugin"...
Using /home/x_fahkh/.cache/torch_extensions as PyTorch extensions root...
Loading extension module bias_act_plugin...
Done setting up PyTorch plugin "bias_act_plugin".
Setting up PyTorch plugin "upfirdn2d_plugin"...
Using /home/x_fahkh/.cache/torch_extensions as PyTorch extensions root...
Loading extension module upfirdn2d_plugin...
Done setting up PyTorch plugin "upfirdn2d_plugin".

Progress to next stage:   0%|          | 0/200000 [2:05:55<?, ?it/s]
/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 33 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/run_gmpi.py", line 115, in <module>
    main()
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/run_gmpi.py", line 49, in main
    run_exp(**vars(args))
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/run_gmpi.py", line 110, in run_exp
    mp.spawn(train, args=(num_gpus, config, master_port, run_dataset), nprocs=num_gpus, join=True)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 6 terminated with signal SIGBUS

```
Can You Please help me out in this....

**Comment by Xiaoming-Zhao** [comment]
I do not think `SIGBUS` is a GPU error signal. I think it means there is something off in the RAM etc.

From the log, it seems like the training has gone for 657 iterations, which means the code is fine. I would recommend keeping an eye on the RAM usage, e.g., running out of memory. Hope this helps.

**Comment by VIROBO-15** [comment]
I have even reduced the batch_size from 4 to 2 but still I am facing the same issue.
I have been using 8 NVIDIA A100 GPUs, with 40GB Memory each. 
Do you still think that  running out of memory may be an issues?

**Comment by Xiaoming-Zhao** [comment]
Maybe I mis-express myself. I think the GPU memory is fine. I am talking about RAM. `SIGBUS` is not an error signal for GPU. See [this link](https://en.wikipedia.org/wiki/Bus_error).
