### ISSUE TITLE
I got error when I start to train

### ISSUE THREAD

**Issue by parkjh688** [apple/ml-gmpi#20]
Hi, I got error below when I start to train model with this command `CUDA_VISIBLE_DEVICES=2,3,4,5,6 python launch.py --run_dataset FFHQ256 --nproc_per_node 0 --task-type gmpi --run-type train master_port 8378`  but I can't figure out the reason.
 
I guess this error is occurred inside train.py's 313 code line if rank == 0:
But I'm not sure. If anyone has solved the problem, please help!

```
Setting up PyTorch plugin "bias_act_plugin"...
Using /root/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu113/bias_act_plugin/build.ninja...
Building extension module bias_act_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module bias_act_plugin...
Done setting up PyTorch plugin "bias_act_plugin".
Traceback (most recent call last):
  File "/data/eden/ml-gmpi/run_gmpi.py", line 115, in <module>
    main()
  File "/data/eden/ml-gmpi/run_gmpi.py", line 49, in main
    run_exp(**vars(args))
  File "/data/eden/ml-gmpi/run_gmpi.py", line 110, in run_exp
    mp.spawn(train, args=(num_gpus, config, master_port, run_dataset), nprocs=num_gpus, join=True)
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV
/opt/conda/envs/gmpi/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d
```

**Comment by Xiaoming-Zhao** [comment]
Do you mind posting the full traceback? Thanks

**Comment by Xiaoming-Zhao** [comment]
BTW, is `--nproc_per_node 0` a typo or you indeed called the command with it? Based on the context, it seems like it should be `--nproc_per_node 5`?

**Comment by parkjh688** [comment]
oh sorry that was wrong command. I've always used `CUDA_VISIBLE_DEVICES=2,3,4,5,6 python launch.py --run_dataset FFHQ256 --nproc_per_node 2 --task-type gmpi --run-type train master_port 837` 

And now I'm using Docker. 

- torch  version: 1.12.1
- CUDA Version: 11.4 
- GPU type : NVIDIA A100
- gcc version : 7.5.0

**Comment by Xiaoming-Zhao** [comment]
Thanks for the clarification. Do you mind posting the full traceback then? Thanks

**Comment by parkjh688** [comment]
I tried --nproc_per_node 1 before but it doesn't work.
But I think that I solve this problem with 2nd advice what you said although I got another error like this.

````
2023-03-27 02:20:19,446 New epoch 0.

Total progress:   0%|                                                                                                                                          | 0/5001 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/data/eden/ml-gmpi/run_gmpi.py", line 115, in <module>
    main()
  File "/data/eden/ml-gmpi/run_gmpi.py", line 49, in main
    run_exp(**vars(args))
  File "/data/eden/ml-gmpi/run_gmpi.py", line 110, in run_exp
    mp.spawn(train, args=(num_gpus, config, master_port, run_dataset), nprocs=num_gpus, join=True)
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/eden/ml-gmpi/gmpi/train.py", line 416, in train
    for batch_i, batch_data in enumerate(dataloader):
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/eden/ml-gmpi/gmpi/datasets.py", line 108, in __getitem__
    X = pyspng.load(f.read())
  File "/opt/conda/envs/gmpi/lib/python3.8/site-packages/pyspng/lib.py", line 48, in load
    arr = c.spng_decode_image_bytes(data, cfmt)
RuntimeError: pyspng: could not decode image size


/opt/conda/envs/gmpi/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by parkjh688** [comment]
I tried the 1st one already but it didn't work.
So I tried 2nd and it seems to solve the issue but when I run the same command `NCCL_P2P_DISABLE=1 CUDA_VISIBLE_DEVICES=5,6 python launch.py --run_dataset FFHQ256 --nproc_per_node 2 --task-type gmpi --run-type train master_port 8378`, the same error sometimes occurs.

**Comment by Xiaoming-Zhao** [comment]
Thanks for your information. Several questions:

1. Do you mind posting the full traceback? I need that to see the exact message. In your original message, the traceback ended on `warnings.warn('resource_tracker: There appear to be %d`. I guess there is something else after it. So please paste the entire traceback messages if possible.

2. For the following
> But I also tried the second solution, and it seems to have solved the issue because it moved on to the next error

What is the **new** error message?

3. For the following
> However, when I run the same command NCCL_P2P_DISABLE=1 CUDA_VISIBLE_DEVICES=5,6 python launch.py --run_dataset FFHQ256 --nproc_per_node 2 --task-type gmpi --run-type train master_port 8378, the same error sometimes occurs.

Since the `NCCL_P2P_DISABLE` trick works, then it is an NVLink issue with a large probability. Regarding this, I guess you need to specify `CUDA_VISIBLE_DEVICES` to the combinations starting with even numbers, e.g., `0,1`, `2,3`, `4,5`, `6,7`. NVLink has some weird setup that the combination starting with an odd number may fail.

**Comment by parkjh688** [comment]
1.
Oh I want to show the full trace but the error is finished at the `warnings.warn('resource_tracker: There appear to be %d`.

2.
The new error message is occurred by `X = pyspng.load(f.read())` in dataset.py. 
Maybe the image file is not a png or path problem something.

3. 
I didn't know that. Thanks! I have 8 GPU which is 0 - 7th. Then I'll try various GPU combinations.

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for the clarification.

Regarding the issue of `pyspng`, it may be due to the package itself since all files are png. If this is the case, this may help: https://github.com/apple/ml-gmpi/issues/1#issuecomment-1192065354

**Comment by parkjh688** [comment]
Thanks!
