### ISSUE TITLE
Great Work!!!! Few queries regarding the evaluation code

### ISSUE THREAD

**Issue by VIROBO-15** [apple/ml-gmpi#3]
Hi....

I have used same script as provided the documentation for the evaluation code 
Script : 
bash {GMPI_ROOT}/gmpi/eval/eval.sh {GMPI_ROOT} FFHQ256 20220727_102024290372 ${Deep3DFaceRecon_PATH}  debug 

But I am getting some error in calculating FID and KID Can you Please help me in this :

real_dir:  /proj/cvl/users/x_fahkh/mn/ml-gmpi/runtime_dataset/real_data/FFHQ256/FFHQ_real_res_256_n_50000 

Traceback (most recent call last):
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/prepare_fake_data.py", line 280, in <module>
    main(opt)
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/prepare_fake_data.py", line 96, in main
    config = Config(init_dict=torch.load(opt.exp_config, map_location="cpu")["config"])
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/proj/cvl/users/x_fahkh/mn/ml-gmpi/ckpts/gmpi_pretrained/20220727_102024290372/config.pth'

Compute FID/KID from 
real: /proj/cvl/users/x_fahkh/mn/ml-gmpi/runtime_dataset/real_data/FFHQ256/FFHQ_real_res_256_n_50000
fake: /proj/cvl/users/x_fahkh/mn/ml-gmpi/ckpts/gmpi_pretrained/20220727_102024290372/planes_96_n_50000/psi_1.0/fid_kid/rgb

Creating feature extractor "inception-v3-compat" with features ['2048']
Extracting features from input1
Traceback (most recent call last):
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/compute_fid_kid.py", line 29, in <module>
    verbose=True,
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/metrics.py", line 239, in calculate_metrics
    featuresdict_1 = extract_featuresdict_from_input_id_cached(1, feat_extractor, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 372, in extract_featuresdict_from_input_id_cached
    featuresdict = fn_recompute()
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 360, in fn_recompute
    return extract_featuresdict_from_input_id(input_id, feat_extractor, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 342, in extract_featuresdict_from_input_id
    input = prepare_input_from_id(input_id, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 275, in prepare_input_from_id
    return prepare_input_from_descriptor(input_desc, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 255, in prepare_input_from_descriptor
    f'Input descriptor "input" field can be either an instance of Dataset, GenerativeModelBase class, or a string, '
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/helpers.py", line 9, in vassert
    raise ValueError(message)
ValueError: Input descriptor "input" field can be either an instance of Dataset, GenerativeModelBase class, or a string, such as a path to a name of a registered dataset (cifar10-train, cifar10-val, stl10-train, stl10-test, stl10-unlabeled), a directory with file samples, or a path to an ONNX or PTH (JIT) module

Can you Please help me in this......

**Comment by Xiaoming-Zhao** [comment]
From the error message, it seems like you do not have checkpoints at `/proj/cvl/users/x_fahkh/mn/ml-gmpi/ckpts/gmpi_pretrained/20220727_102024290372`. Put your checkpoints there with structure:
```
+-- ckpts
|  +-- gmpi_pretrained
|  |  +-- 20220727_102024290372
|  |  |  +-- config.pth
|  |  |  +-- discriminator.pth
|  |  |  +-- generator.pth
|  |  |  +-- ema.pth
|  |  |  +-- ema2.pth
```

**Comment by VIROBO-15** [comment]
Thanking You @Xiaoming-Zhao for replying... I have fixed the issue but till there are some issue which I am not able to figure out

Load weights from /proj/cvl/users/x_fahkh/mn/ml-gmpi/ckpts/gmpi_pretrained/20220727_102024290372/generator.pth


Load weights from /proj/cvl/users/x_fahkh/mn/ml-gmpi/ckpts/gmpi_pretrained/20220727_102024290372/ema2.pth

Traceback (most recent call last):
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/prepare_fake_data.py", line 280, in <module>
    main(opt)
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/prepare_fake_data.py", line 172, in main
    generator = setup_model(opt, config, metadata, mpi_xyz_input, mpi_xyz_only_z, vis_mesh=False, device=device)
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/common.py", line 144, in setup_model
    ema.load_state_dict(ema_state_dict)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_ema/ema.py", line 299, in load_state_dict
    "Tried to `load_state_dict()` with the wrong number of "
ValueError: Tried to `load_state_dict()` with the wrong number of parameters in the saved state.

Compute FID/KID from 
real: /proj/cvl/users/x_fahkh/mn/ml-gmpi/runtime_dataset/real_data/FFHQ256/FFHQ_real_res_256_n_50000
fake: /proj/cvl/users/x_fahkh/mn/ml-gmpi/ckpts/gmpi_pretrained/20220727_102024290372/planes_96_n_50000/psi_1.0/fid_kid/rgb

Creating feature extractor "inception-v3-compat" with features ['2048']
Extracting features from input1
Traceback (most recent call last):
  File "/proj/cvl/users/x_fahkh/mn/ml-gmpi/gmpi/eval/compute_fid_kid.py", line 29, in <module>
    verbose=True,
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/metrics.py", line 239, in calculate_metrics
    featuresdict_1 = extract_featuresdict_from_input_id_cached(1, feat_extractor, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 372, in extract_featuresdict_from_input_id_cached
    featuresdict = fn_recompute()
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 360, in fn_recompute
    return extract_featuresdict_from_input_id(input_id, feat_extractor, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 342, in extract_featuresdict_from_input_id
    input = prepare_input_from_id(input_id, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 275, in prepare_input_from_id
    return prepare_input_from_descriptor(input_desc, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/utils.py", line 255, in prepare_input_from_descriptor
    f'Input descriptor "input" field can be either an instance of Dataset, GenerativeModelBase class, or a string, '
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch_fidelity/helpers.py", line 9, in vassert
    raise ValueError(message)
ValueError: Input descriptor "input" field can be either an instance of Dataset, GenerativeModelBase class, or a string, such as a path to a name of a registered dataset (cifar10-train, cifar10-val, stl10-train, stl10-test, stl10-unlabeled), a directory with file samples, or a path to an ONNX

**Comment by Xiaoming-Zhao** [comment]
@VIROBO-15 Thanks a lot for reporting this issue. I just submitted a commit to fix this. Hope that helps.
